apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: __namespace__
spec:
  type: LoadBalancer
  selector:
    app: proxy
    release: __release_tag__
  ports:
    - protocol: TCP
      name: proxy
      port: 32001
      targetPort: 32001
      nodePort: 32001
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
      release: __release_tag__
  template:
    metadata:
      labels:
        app: proxy
        release: __release_tag__
    spec:
      volumes:
      - name: odp-nginx-sec
        secret:
          secretName: odp-nginx-sec
      containers:
        - name: nginx
          image: '__docker_registry_server__/odp:nginx.__release__'
          ports:
            - containerPort: 32001
          volumeMounts:
            - name: odp-nginx-sec
              mountPath: "/usr/share/nginx/keys"
              readOnly: true
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret